version: 3.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
before_build:
  - nuget restore ".\SafeMapper.sln"  
configuration: Release
build:
  project: .\SafeMapper.sln
  publish_nuget: true
  verbosity: minimal
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '3.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
- path: '*.nupkg'
  name: Nuget
environment:
    COVERALLS_REPO_TOKEN:  
       secure: K+fCPAUxXxW0g4oxV+/Y8oYyiiYKagU4gOQ9SRP5AH9Si3uACrS4D1kKxOsXs/Bp
after_test:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user "-target:packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" "-targetargs:SafeMapper.Tests\bin\%CONFIGURATION%\net45\SafeMapper.Tests.dll /noshadow" "-filter:+[SafeMapper*]* -[SafeMapper.Tests*]*" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml